# Generated by Django 2.0.1 on 2018-03-06 10:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None)),
                ('booked', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('change_date', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), size=None)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
