# Generated by Django 2.0.1 on 2018-03-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180330_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='booked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='change_date',
            field=models.TextField(default='2018-03-30,'),
        ),
        migrations.AlterField(
            model_name='room',
            name='user',
            field=models.TextField(default='0,'),
        ),
    ]
