# Generated by Django 2.0.1 on 2018-03-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180306_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
