# Generated by Django 2.0.1 on 2018-03-31 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_room_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('booked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='room',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
    ]
