# Generated by Django 2.0.1 on 2018-03-31 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_note_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-timestamp']},
        ),
    ]
